language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

services:
  - mongodb

env:
  - travis=true host=127.0.0.1

before_script:
  - pecl install mongodb
  - phpenv config-add travis_php.ini
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: phpunit --bootstrap autoload.php tests
