language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

services:
  - mongodb

before_script:
  - pecl install mongodb
  - phpenv config-add travis_php.ini
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: phpunit --bootstrap autoload.php tests
